nylira/prism-break

source/db/en-projects.json
MediaCrush as a service shuts down today.
=> Removed MediaCrush as a Web Service

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Hello again,
Cryptsetup moved their development to gitlab, and the link pointing to **encfs** was broken.
Cheers
=> fixed couple broken links

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Closes #1010.
---
@Zegnat So just have the same url as the source code, because the license seems to be an embedded comment in the source code anyway?
=> Add license url to ProtectedText

source/views/about/media.jade
Ref #1260.
---
I wouldn't say it "closes" #1260 because there are still these broken links which do not seem to have archive.org backups (they either were not indexed or the snapshots themselves were all broken too):
- Röll, Nadja. http://www.srf.ch/k.text-blocktur/im-fokus/weblese/surfen-ohne-dass-die-nsa-zuschaut
- Luckerson, Victor. http://business.time.com/2013/06/20/the-anonymous-internet-privacy-tools-grow-in-pop.text-blockarity-following-nsa-revelations/
- Informare per resistere. http://www.informarexresistere.fr/2013/07/08/blocca-il-controllo-del-governo-usa-s.text-blockle-tue-attivita-online-liberati-da-prism/
Additionally, this one seems to be behind a paywall (and same with the archive.org versions), which I'm not sure is a problem but might be:
- de Sá, Nelson. …
=> Fix some broken media links with archive.org backups

source/db/ru-projects.json
I think this might be a mistake somehow because none of the other language files have gorhill's one? This may eventually be changed back (due to #1291) anyway, but for now I think fixing it would reduce/stop any possible confusion.
=> Fix uBlock link in source/db/ru-projects.json

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
It clearly looks like everything in the `source/db/*.json` files are supposed to be alphabetically arranged, but probably overtime there's been a lot of mix ups. Obviously, strictly keeping it alphabetical all the time is probably a waste of time. But I think I and maybe others would find it easier for the future if it is a bit more sorted. (Even just to navigate, because they are large files in terms of number of lines.)
Ftr, I used a small script to do this and hence why you can see some tabs have been changed to spaces (as in, just the whitespace indentation, not actual content). Only changed `source/db/*.json` files because I don't think any other files are large enough to consider this anyway.
Tested with `make reset`, doesn't seem to mess anything up.
=> Sort db json files by 'slug' key

source/stylesheets/screen.styl
With a browser height at 724 px (basically fullscreen browser on a 1366x768 res screen minus some panels), I just miss out on the fix. I know this is probably arbitrary and depends on users fonts or something, but 755px seems to be the margin for me where I can I see all categories, so I'm hoping that's acceptable. At 724 px, Web Search and World Maps are cut off (although I can still some of the top of Web Search) on GNU/Linux and Windows. (Obviously the other categories are not long enough.)
This is probably due to the addition of the Bookmark Sync category.
=> Fix sidebar being too long for GNU/Linux and Windows categories

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Ref #1349.
---
At least for now, until someone decides what to actually do in #1349, because July 5th is not far away.
=> Add notice about Bookie.io shutting down

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
[Source] [1]
[1]: https://gitorious.org/statusnet/gnu-social/source/5308e04e83f4a3f04e6d8bf80b177e7208dbac58:COPYING
=> update GNU social urls for switch to gitlab.com from gitorious.org

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Closes #1369.
---
I agree with @strugee. The warning on https://arkos.io/ should be enough to warrant this, but if you want more, the latest tag is still less than 1: https://github.com/cznweb/genesis/releases.
=> give experimental tag to arkOS

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
After this change, the only differences (I think) left are:
1. "fr-projects.json" has Wikipedia urls for the "Disconnect",
"EtherCalc" and "Kamailio" projects, which no other locale has.
2. "zh-CN-projects.json" has translations for the "I2P" and "Ixquick"
projects' "notes" section, which no other locale has, as introduced
by b5495f7 from #932.
- Notice that in the diff of b5495f7, the "notes" section for both
these projects were empty before the change.
3. "fi-projects.json" has a translation for the "Off-the-Record
Messaging" project's "notes" section, which no other locale has, as
introduced by 1bd7801 from #1177.
- Notice that in the diff of 1bd7801, the "notes" section for this
project was empty before the change.
1 however should not be a problem because it does not look like there …
=>  synchronize missing/unequal metadata across all locales

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Ref #1388.
---
@antiprismca So I only put it under the "Servers" category as @Zegnat agreed with me in #1388. I didn't  change anything else.
=> AntiPrism should only be listed under the "Servers" category

CONTRIBUTING.md
PRISM-Break is largely driven by community participation in discussions
surrounding the inclusion or exclusion of various solutions. Given that
user privacy is (by definition) a very personal matter and that the
security community in general tends to have strong opinions, my
observation is that many issues that come up are fairly highly changed
even before somebody looses their cool or makes a nasty remark.
I think it would behoove the project to officially adopt a Code of
Conduct document that can be considered binding on participants in
discussion. Getting this into the repository early before any particular
major issue between participants comes up gives everybody something to
reference and a relative standard by with to judge a situation. This
could potentially save some grief vs. the …
=> Adopt a Code of Conduct for project participants

source/views/categories/index.jade
https://prism-break.org/en/categories/
I don't think this page is linked to anywhere, I came there by removing the end of the url.
=> Fix category links in /categories/

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
This also moves kontalk from the bottom to its alphabetical place in
de-projects.json and en-projects.json.
---
BTW, thanks to #1482, you can now close #276 and #1408. :)
=> add missing translation stubs for kontalk

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
From #1461:
- Add Adblock Edge to BSD, GNU/Linux, OS X and Windows.
- Add NoScript to Android.
- Add OpenNIC to Routers.
- Add I2P to Android.
(Self-Destructing Cookies is already in Android now.)
Closes #1461.
=> Various program category placement amendments

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
This removes Privacy Badger from the list of Android-compatible projects. Disconnect wasn't in the Android list to begin with; I suspect #1606's OP got the addon confused with the web site.
Fixes #1606.
=> Remove Privacy Badger from Android recommendations

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Firefox is available on iOS as well, although it's essentially Webkit with a Firefox UI around it. It doesn't share in Safari's syncing, cookies and other state data though.
EDIT: Link: https://www.mozilla.org/en-US/firefox/ios/
=> Add Firefox as a web browser alternative on iOS.

README.md
io.js was merged back into Node.js quite a while ago.
=> Remove README.md references to io.js

source/db/ar-projects.json
I'm working on a complete overhaul of the Makefile and ran into not being able to build all the languages. It looks like this came from 00be7c1 — somebody must not have actually tried building this 😉 .
(The good news is with the new Makefile and proper dependencies a failed make knows what language didn't finish and `make all` picks up where it left off!)
=> Remove bogus content outside of JSON in ar language data

Makefile, README.md, package.json, source/functions/build.ls, source/functions/find-missing-localizations.ls, source/functions/load-data.ls
WIP for feedback; do not merge. /cc @nylira because most of this was written by you.
This change makes it so that when building localized pages, the English project data is used as a default if a localized version is not provided. This means that when adding new projects, contributors can update the English data and be done with it, as opposed to patching all 23 language files. Updates to existing projects also only need to patch files that have already been localized.
One big downside to this is that it's no longer quite as obvious what's not localized. I have a plan to add some Make targets which will provide a list, per-language, of what still needs to be added. This will make localization via the GitHub web interface slightly more challenging, but I think it's worth it.
However! This …
=> Make localizations inherit from English JSON data

CONTRIBUTING.md
For https://github.com/nylira/prism-break/pull/1702 I was under the impression I needed to add the English originals to all the files because of this confusing sentence.
Contributing translations is a section below, so that already explains it.
=> Remove confusing sentence about adding to other language files

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Closes #1815, see issue for discussion.
~~Note this PR one whitespace cleanup commit not related to this function — but that makes these sort of removals much easier. This can/will conflict if other PRs are merged first. Doing these removals manually is painful compared to automating it with a JSON filter. I can easily redo this if other PR merges break it before it get merged, just ping me here.~~
=> Remove obsolete Random Agent Spoofer

package.json
`jsonlint` is unmaintained and broken due to npm registry changes; see zaach/jsonlint#105. This will be failing all CI jobs that run in the near future, so we should fix it now.
I still need to update `package-lock.json` before this can be merged, self-assigning in an attempt not to forget.
=> Switch to jsonlint2

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Closes #1866.
Should have been covered in #1815 but I missed the comment.
Removed with:
find -name '*-projects.json' -print |
while read file; do
jq '[.[] | select(.slug != "request-policy")]' < $file |
sponge $file
done
=> Remove RequestPolicy addon not supported in FF57+

source/db/zh-CN-projects.json
Supersedes #1714.
That pull request also includes translation update, which doesn't cleanly apply on top of current master. I might not be able to salvage this work because I don't know Chinese.
=> Remove dukgo.com from zh-CN locale

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
DNSCrypt Proxy has been rewritten in Go under ISC license and site has moved to https://dnscrypt.info. Closes #1858.
=> Update DNSCrypt metadata

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Up1 is not a centralized web service, but rather a self-hosted service. Currently there is a lot of inconsistency in usage of this badge, but it seems to me that the only meaningful distinction is to mark centralized web services.
Otherwise, all networking server-client software would have to be marked as "web service", because user will always use some particular instance of it (think of OpenVPN and multiple OpenVPN providers).
Notably, Kolab, Nextcloud, Riot are self-hosted services that currently do not have this badge. This pull request adds Up1 to the list.
Specifically compare Kolab (doesn't have "web service" badge) and Kolab Now (does have "web service" badge). I think this example captures the essence of when this badge is applicable.
=> Remove "web service" badge from Up1

CONTRIBUTING.md, README.md
This adds a direct qwebirc link to #prism-break IRC channel so that people that do not regularly use IRC can easily participate, without opening issues for questions.
/cc @strugee
=> Link Freenode channel in README, resolves #1914

CONTRIBUTING.md
Remove defunct mirrors. Unfortunately, that includes all mirrors listed in `CONTRIBUTING.md`.
=> Remove mirrors (defunct)

source/db/en-projects-rejected.ls
While Facebook can conceivably used as an email service, it is not regarded as such and very few people use and/or know about this functionality. 
I think that putting Facebook in this category is confusing, hence this pull request.
=> Remove Facebook from Email categories

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Openswan has not been updated for the most part since 2017:
https://github.com/xelerance/Openswan/commits/master
Strongswan does the same thing but is way better maintained:
https://github.com/strongswan/strongswan
=> Drop Openswan

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Windows only. Last release dates back to 09.07.2014. Does not support EFI boot or GPT labels, if one uses it on such system, makes it unbootable. Does not support non-alphanumeric passwords.
See: https://diskcryptor.net/wiki/Main_Page
=> Drop DiskCryptor

source/db/en-projects.json
Unfriendly to contributions, no public commit history, just squashed
release commits:
https://github.com/antiprismca/OpenELEC-Antiprism/commits/master
Haven't been updated for a long time (since early 2017), which
is very bad for a distribution. Large gaps between updates.
Not clear how this is any better than OpenELEC.
=> Drop Antiprism

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
Last release was on 2013-03-20:
https://sourceforge.net/projects/semanticscuttle/files/SemanticScuttle/v0.98/
=> Drop Semantic Scuttle

source/db/ar-projects.json, source/db/ca-projects.json, source/db/de-projects.json, source/db/el-projects.json, source/db/en-projects.json, source/db/eo-projects.json, source/db/es-projects.json, source/db/fa-projects.json, source/db/fi-projects.json, source/db/fr-projects.json, source/db/he-projects.json, source/db/hi-projects.json, source/db/io-projects.json, source/db/it-projects.json, source/db/ja-projects.json, source/db/nl-projects.json, source/db/no-projects.json, source/db/pl-projects.json, source/db/pt-projects.json, source/db/ru-projects.json, source/db/sr-Cyrl-projects.json, source/db/sr-projects.json, source/db/sv-projects.json, source/db/tr-projects.json, source/db/zh-CN-projects.json, source/db/zh-TW-projects.json
We already list Etesync, which does the same thing as Davdroid while
being end-to-end encrypted, as in not leaking any data to the server.
=> Drop DAVDroid in favor of Etesync
