nylira/prism-break

- source/db/en-projects.json
Updated entry as per current status.
> available for Firefox for Android since v 0.9.1.0

- .travis.yml
- CONTRIBUTING.md
- README.md
- added `.travis.yml` for continuous integration with [travis-ci.com](https://travis-ci.com)
- added a mirror
- some markdown
> Repository improvements

- README.md
Ref #1321.
---
In case this helps (because I completely forgot about it as I realised in #1321, but also any potential newcoming contributors may not even know about it either). Not sure if it is the best wording?
> Add note about the "pull request accepted" label in the README

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
Ref #1322.
---
Not sure if it's a traditional "File Storage & Sync" app, but pr on request of @devvv4ever in #1322. Your call in the end, but do note that @devvv4ever is a DAVdroid developer.
@rfc2822 (also DAVdroid developer)
> Add DAVdroid to File Storage & Sync category

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Remove experimental tag from DAVdroid

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
[Source] [1]
[1]: https://movim.eu/en/node/389
> update Movim urls for switch to Github

- source/db/en-projects-rejected.ls
Closes #1368.
---
I think @strugee is right, Bitlocker comes with Windows Server 2008 and later according to wikipedia: https://en.wikipedia.org/wiki/BitLocker
> add BitLocker to Servers category

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Update broken Enigmail license url

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
It's now out of beta: http://www.pcworld.com/article/2961068/privacy/eff-tracker-smashing-privacy-badger-exits-beta.html
> Update Privacy Badger status

- source/db/zh-CN-projects.json
Translate the introduction of SMSSecure which was introduced by [#1268](https://github.com/nylira/prism-break/pull/1268)
> Translate the introduction of SMSSecure

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
Official webpage is http, not https. Sorry about that. Also corrected the platforms, I didn't knew about the Web Services platform.
> Important fixes of previous pull request.

- source/db/de-projects.json
I have just found a stupid typo. And btw I also improved translation. It seems I was a little bit tired.
I'm sorry :-(
> fixed typo and improved german translation for Kontalk

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Update source code link for GNU Social

- source/db/de-projects.json
- source/db/en-projects.json
- source/db/es-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/nl-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/zh-CN-projects.json
Author of Decentraleyes here. First off, I'm quite honored to see the add-on listed, as this has been my "go to" site for spotting alternatives for quite some time now.
Thanks to a crowd-sourced add-on [translation effort](https://github.com/Synzvato/decentraleyes/issues/44) (and the volunteers involved), I'm able to contribute some additional locales for Decentraleyes to this project. I hope it helps!
I had to make slight changes to the notes, mainly because the first few sentences are no longer present on Decentraleyes' download page, and are not available in multiple languages. I have also changed "Adblock Plus" to "Request Policy" to tailor the information to your main audience.
**Additions**: Dutch, Finnish, French, German, Polish, Portuguese, Simplified Chinese, and Spanish.
> Localize Decentraleyes

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
https://tails.boum.org/doc/anonymous_internet/i2p/index.en.html
> Tails support I2P

- source/locales/ar.json
- source/locales/ca.json
- source/locales/de.json
- source/locales/el.json
- source/locales/eo.json
- source/locales/es.json
- source/locales/fa.json
- source/locales/fi.json
- source/locales/fr.json
- source/locales/he.json
- source/locales/hi.json
- source/locales/io.json
- source/locales/it.json
- source/locales/ja.json
- source/locales/nl.json
- source/locales/no.json
- source/locales/pl.json
- source/locales/pt.json
- source/locales/ru.json
- source/locales/sr-Cyrl.json
- source/locales/sr.json
- source/locales/sv.json
- source/locales/tr.json
- source/locales/zh-CN.json
- source/locales/zh-TW.json
Added Enterprise suite category to all locales language files.  Please
merge.  Thanks
> Added Enterprise Suite Category

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Add missing translation stubs for Android Password Store

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
As was discussed in #1586 and #904
> Remove Firefox OS (discontinued)

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
https://github.com/nylira/prism-break/issues/1592
> Correct Ixquick links

- README.md
- source/functions/slugify.ls
- source/views/layouts/footer.jade
Added few HTTPS Links. Changed Stylus Language link and Jade Language link (Jade is now renamed to [Pug](https://github.com/pugjs/pug#rename-from-jade)).
> HTTPS Links

- Makefile
Thanks to @alerque for (indirectly) pointing this out in #1627 :)
> Simplify Makefile build targets

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Remove ChatSecure Android

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Remove dukgo.com

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
Closes #1661
@strugee I guess that it is OK to remove it.
> Remove CSipSimple

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Updated FreeOTP URLs

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
The path to the LICENSE inside the repository has changed. See k9mail/k-9#1712
> update link to k-9 license file

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
WIP, do not merge - this diff is large (because my sed commands were aggressive) and I _have not read it yet_.
Remove a bunch of duplicated Mozilla stuff and sync up the source code link with desktop Firefox.
> Refresh Firefox mobile metadata

- .travis.yml
- Makefile
- package.json
- source/locales/zh-TW.json
Not sure if this is actually the best way to do this since as I've said before, I am not very good at Makefiles :P
It does work, however.
> Add `lint` Make target to lint JSON

- .github/ISSUE_TEMPLATE.md
I didn't spend much time on this, but it's better than nothing and will hopefully cut back on the number of duplicates filed.
> Add very basic issue template

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Remove Thunderbird from XMPP

- source/db/en-projects.json
The current link is a 404, my change fixes that.
> Fix Autistici hyperlink

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> update more autistici.org links

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Update Qubes URLs

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
I did a basic pass through and have double-checked all the files, but I haven't looked directly at the diff. Also I didn't feel like waiting for an entire build locally so we'll have to see if CI passes.
> Nuke Pidgin

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
Closes #1659, see extensive discussion there.
~~Note this PR has a duplicate commit with #1852. Whichever one is merged first will suffice, the second one can be rebased. Doing these removals manually is painful compared to automating it with a JSON filter. I can easily redo these if other PR merges break them before they get merged, just ping me here.~~
> Remove xabber

- CONTRIBUTING.md
> Fix render of Code of Conduct link

- source/db/en-projects.json
> Mark eCryptfs as audited

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Update Namecoin metadata

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Drop Profanity

- source/db/en-projects-rejected.ls
> Add Snapchat to the list of proprietary services

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
> Drop pfSense

- source/db/en-projects.json
> Mark OpenKeychain as audited

- source/locales/zh-CN.json
Putting a translation there in case of a empty bar seeming weird.
Maybe not a really good translation. Suggestion welcomed.
> Translate "Onion services" at zh-cn

- Makefile
- README.md
- package.json
- yarn.lock
Serves `public/` at http://localhost:8080.
> Add `make serve` phony target

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
Hasn't been updated since 2015: https://github.com/buddycloud
> Drop Buddycloud

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
Disconnect comes with nonfree software: https://github.com/disconnectme/disconnect/issues/366
Repository has seen very little activity since 2015 (4 commits total): https://github.com/disconnectme/disconnect/commits/master
> Drop Disconnect

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
Documentation only in Spanish, hasn't been updated since 2015.
> Remove LibreVPN

- source/db/en-projects-rejected.ls
- source/functions/build.ls
Renames proprietary projects to their upstream names and sorts those alphabetically. Removes some duplicates and deprecated projects.
> Cleanup proprietary projects

- source/db/ar-projects.json
- source/db/ca-projects.json
- source/db/de-projects.json
- source/db/el-projects.json
- source/db/en-projects.json
- source/db/eo-projects.json
- source/db/es-projects.json
- source/db/fa-projects.json
- source/db/fi-projects.json
- source/db/fr-projects.json
- source/db/he-projects.json
- source/db/hi-projects.json
- source/db/io-projects.json
- source/db/it-projects.json
- source/db/ja-projects.json
- source/db/nl-projects.json
- source/db/no-projects.json
- source/db/pl-projects.json
- source/db/pt-projects.json
- source/db/ru-projects.json
- source/db/sr-Cyrl-projects.json
- source/db/sr-projects.json
- source/db/sv-projects.json
- source/db/tr-projects.json
- source/db/zh-CN-projects.json
- source/db/zh-TW-projects.json
Hasn't been updated since 2016, see:
https://github.com/i2p/i2p.syndie/commits/master
Also, only works with I2P.
> Drop Syndie
